---
- name: test drupal install
  hosts: all
  user: root

  vars_files: 
    # for secret.mysql.users.root.password
    # and secret.mysql.users.drupal.password
    - secret/vars.yml

  vars:
    # This overrides the default used by the mysql role.  We can't
    # pass it as a parameter to an invocation here without invoking it
    # twice (since the drupal role depends on it).
    mysql:
      users:
        root:
          password: '{{ secret.mysql.users.root.password }}'

  roles:
    - role: drupal-vhost
      drupal_vhost:
        id: default
        state: present 
        # ...Note, seems we cannot rely on the default 'state'
        # parameter defined in the drupal_vhost role without getting
        # an UndefinedError, for reasons I don't fully understand but
        # presumably related to the use of the jinja2 expression in
        # the role's meta/main.yml. We must define it explicitly for
        # this to work.

        makefile: panopoly.makefile
        profile: panopoly
        vhost:
          id: drupal
          server_name: drupal.nonesuch.com
        db:
          name: drupal
          user: drupal
          password: '{{ secret.mysql.users.drupal.password }}'

        site:
          mail: drupal@{{ inventory_hostname }}
          name: Drupal Site
        admin:
          account: admin
          mail: 'webmaster@{{ inventory_hostname }}'
          password: '{{ secret.drupal.users.admin.password }}'




