---
dependencies:
  - drupal

  - role: mysqldb
    mysqldb:
      name: ${drupal_vhost.db.name}
      users:
        - username: ${drupal_vhost.db.user}
          password: ${drupal_vhost.db.password}
          host: localhost
          priv: '*:ALL'

  - role: apache-vhost
    apache_vhost:
      id: ${drupal_vhost.vhost.id}
      server_name: ${drupal_vhost.vhost.server_name}
      vhost_addr: ${drupal_vhost.vhost.vhost_addr}
      server_admin: ${drupal_vhost.vhost.server_admin}
      server_name: ${drupal_vhost.vhost.server_name}
      server_aliases: ${drupal_vhost.vhost.server_aliases}
      enable: ${drupal_vhost.vhost.enable}
      template: ${drupal_vhost.vhost.template}
      document_root: ${drupal.sites_install_dir}/${drupal_vhost.id}
#      cgi_bin: ${drupal_vhost.vhost.cgi_bin} # FIXME causes a merge_hash error
      log_level: ${drupal_vhost.vhost.log_level}
      access_log_path: ${drupal_vhost.vhost.access_log_path}
      error_log_path: ${drupal_vhost.vhost.error_log_path}
      remove: ${drupal_vhost.vhost.remove}
