---
- name: mysqldb | Sanity check 
  action: fail msg="default mysqldb.* definitions must be overridden"
  when: mysqldb.name == 'change_this_to_something_else'


- name: mysqldb | Create MySQL database
  action: mysql_db db="{{mysqldb.name}}" state="{{ mysqldb.state }}"

- name: mysqldb | Create/set the password for each user
  action: mysql_user
          user="{{item.username}}"
          password="{{item.password}}"
          host="{{item.host}}"
          priv="{{mysqldb.name}}.{{item.priv}}"
  with_items: mysqldb.users
  when: "'state' not in item or item.state != 'absent'"

- name: mysqldb | Delete each ex-user
  action: mysql_user user="{{item.username}}" host="{{item.host}}" state="absent"
  with_items: mysqldb.users
  when: "'state' in item and item.state == 'absent'"

